# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a4e13ee51b0cd58b09acedc2ac9da7adea301e35554682576708297894d4281139a49853dcdcbf794ffb3ade26fce2017122cc8c24bc639305e329e5805a82

test:
  secret_key_base: 8fe1b48d36316bf66592287a0fdeb074b5a01cb1e841e62cc5be5052b7bc10f83591660218c59f85a2c0bf02c9643f0c2ec5825fe93f6e09934e646ba575d2d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
